### ISSUE TITLE
Align the map the center of the Template?

### ISSUE THREAD

**Issue by nicedevil007** [alexkn/node-red-contrib-valetudo#1]
Hey alexkn,

first I want to thank you for your nice node <3

Just one small thing I noticed. Would it be possible to cut off  everything out the drawn flat? Or maybe it would be possible to add an offset to align the map more to the left. 

Here a screen on an iPhone XS. It won't fit the screen nicely :(

![grafik](https://user-images.githubusercontent.com/17103076/65724136-0e485c80-e0b0-11e9-8712-7d004bd63074.png)

**Comment by alexkn** [comment]
Did you use my HTML Code Sample for the template node?

`<div>
    <img src="data:image/png;base64,{{msg.payload}}" style="width: 100%;height: auto" />
</div>`

Width 100% should shrink the map to the size of the template node.
So it should be centered automatically.

You can use the crop settings to cut off the parts outside your flat.

**Comment by nicedevil007** [comment]
Hey alex,

yes I did use this but it didn't worked. I tryed the crop and width settings at all but no chance to get it to work like it should.

Unfurtunately my Node-Red keeps freezing when I was using your node while I uninstalled it.
I don't know why for sure but saw anything with rights on the created folders of it. Maybe I give it a try an other time :)

**Comment by nicedevil007** [comment]
Ok, tested it again.

Your node still keeps rebooting node-red on my setup. I guess it is because of the overwhelming messages the S50 is sending to my node-red?

But I tested again the crop and so on... maybe I'm doing it wrong?

![grafik](https://user-images.githubusercontent.com/17103076/66187484-29edcd00-e685-11e9-8e19-1a21a28fd737.png)

**Comment by nicedevil007** [comment]
With the standard settings (crop 0) I get something like this:

![grafik](https://user-images.githubusercontent.com/17103076/66187769-cdd77880-e685-11e9-8e21-f65b5d16aacd.png)

**Comment by alexkn** [comment]
With Defer 2000 the map is drawn every 2 seconds, so overwhelming messages should not be the problem.

Crop x2 and Crop y2 should be larger, all coordinates are measured from the left or top edge.

My config:
![grafik](https://user-images.githubusercontent.com/645022/66230656-f0e54500-e6e4-11e9-8d76-04ec37ad87c6.png)

**Comment by nicedevil007** [comment]
ok think I got it now :)
