### ISSUE TITLE
Valetudo RE: Incorrect Header Check

### ISSUE THREAD

**Issue by nicedevil007** [alexkn/node-red-contrib-valetudo#11]
Hey @alexkn 

tested your node again after switching from my old node-red installation to my new integrated one in ioBroker.
I get this error:

![image](https://user-images.githubusercontent.com/17103076/113027932-f4974200-918a-11eb-9493-ec2b9229498a.png)

I'm using ValetudoRE so I tryed to use valetudo-parse-binmap in front of the valetudo-map-png and the opposit as well.
Still this error.

Like so:
![image](https://user-images.githubusercontent.com/17103076/113028474-99b21a80-918b-11eb-9ac4-33f20ed0af4b.png)

And here an example what valetudo is offering:

![image](https://user-images.githubusercontent.com/17103076/113028103-2e684880-918b-11eb-9d8b-8c38f6341a20.png)

**Comment by alexkn** [comment]
Feel free to send a pull request.

**Comment by nicedevil007** [comment]
Sry don't know what you mean :( Or how to do this. So it is Valetudo RE related and won't be fixed in a future patch/release?

**Comment by alexkn** [comment]
I will not fix it, because I don't use RE.

**Comment by alexkn** [comment]
Something is wrong with your map data.
Valetudo RE should send gziped data which should start with 1F8B instead of 1FEF in your data.

**Comment by hoyohayo** [comment]
Acutally this is not only happening with Valetudo RE. I am on a Roborock S5 Max with Valetudo Version 2021.03.0
 my output of the Map Data is starting as followed: 

<img width="273" alt="Node_Red_Valetudo" src="https://user-images.githubusercontent.com/36436027/114275258-608e6b80-9a11-11eb-89a6-5f1c42e67826.png">

My debug from the output node is showing the same thing "incorrect header".
I am not really sure where the problem is...

**Comment by alexkn** [comment]
@hoyohayo Disable Homeassistant Map Hack in Valetudo MQTT Settings

**Comment by hoyohayo** [comment]
> 
> 
> @hoyohayo Disable Homeassistant Map Hack in Valetudo MQTT Settings

Thanks for the update! That actually helped a lot!

**Comment by alexkn** [comment]
@nicedevil007 
The `EF BF BD` in your map data indicates a failed utf-8 encoding as described here:
https://stackoverflow.com/a/6544206

I assume with your switch to ioBroker you switch to a bad mqtt broker which destroys the binary map data.
You have to fix your mqtt setup.
So this is not a problem of this node.

**Comment by miguelpruivo** [comment]
@alexkn all of a sudden I started to experience this issue with a S50. It was working great before. Do you know what it could be? Thanks!
