### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by nicedevil007** [alexkn/node-red-contrib-valetudo#17]
Hey Alex,

I have this small problem here (at least I hope it is small).

Node-RED Version 2.1.4
Valetudo 2021.12.1
Your NPM Package => Version 3.0

![image](https://user-images.githubusercontent.com/17103076/147655789-2faebdd3-9391-4f0a-b272-27a8661de2ee.png)

![image](https://user-images.githubusercontent.com/17103076/147655870-b3e68384-a84f-477f-956f-8f48e5986bd1.png)

**Comment by alexkn** [comment]
Valetudo RE Support is removed in 3.0

**Comment by nicedevil007** [comment]
I don't use valetudo RE?
This error is coming from your node?

**Comment by alexkn** [comment]
Are you using the parse-binmap node somewhere?

**Comment by alexkn** [comment]
should be fixed in [v3.0.1](https://github.com/alexkn/node-red-contrib-valetudo/releases/tag/v3.0.1)
