### ISSUE TITLE
incompatible with @rand256/valetudo

### ISSUE THREAD

**Issue by nicedevil007** [alexkn/node-red-contrib-valetudo#2]
Hey Alexkn :)

maybe something happened to the API in a release of valetudo?

I get those errors with your node and the map is showing a state of some days or maybe weeks ago. The map on the official valetudo site on my robot is showing correctly.

![image](https://user-images.githubusercontent.com/17103076/68144550-3d19e400-ff34-11e9-9900-81211a297172.png)

**Comment by alexkn** [comment]
Do you run an self compiled version of valetudo?
I still run the Beta 0.4.0 Release and don't have problems.

However, I see that my mqtt node outputs a string as payload, not a buffer like yours.
Can you try to change the data type of the output to "a String" in your mqtt node?

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/68156970-07352980-ff4d-11e9-8995-d88c6597e383.png)

with "a String"

I'm using this Valetudo Version => https://github.com/rand256/valetudo
Because of more Features and so on.

**Comment by nicedevil007** [comment]
Mhh maybe it is because of this?

> Valetudo 0.4.0-RE6 preview
> @rand256 rand256 released this 8 hours ago
> 
> Next release for testing RE version, verified on S55 (fw 1898).
> 
> The most important change in this release:
> 
> Moved map parsing from server-side to clients.
> This way was greatly reduced CPU usage on the device and somewhat lowered RAM consumption.
> Also the network bandwidth usage while watching the map was notably reduced as well.
> 
> At the same time this change made Valetudo RE incompatible with any third party service that relied on the prepared map data published by the device. Thus the required changes were made for valetudo-mapper companion application: now it can not only create PNG map images but also publish parsed map data in the old compatible JSON format.
> 
> As always, I remind everyone the necessity to use valetudo binary with valetudo.conf upstart script from this fork only, as it includes preparations for properly running the service that are missing in the origin script.
> 
>

**Comment by alexkn** [comment]
Yes, with this change, the map parsing has to be done inside the node.

**Comment by nicedevil007** [comment]
Does that mean you will add this in a future release?

If I understand those changes correct it would likely be added to standard valetudo in the near future? :)

That guy (rand256) coded the ability for No-Go Zones and so on for valetudo and they forked it to the original one after he did this ;)

**Comment by alexkn** [comment]
Yes, I want to add it.
But I do not want to break the compatibility with standard valetudo, as long as the changes are not merged.
I think the right way would be to create a converter node.

PS: Grüße zurück ;)

**Comment by rand256** [comment]
> But I do not want to break the compatibility with standard valetudo, as long as the changes are not merged.

You may want to see how it's done in [valetudo-mapper](https://github.com/rand256/valetudo-mapper/commit/c451348bd516a07cdda63a4c415977b6b14822a4) without breaking compatibility with older versions. Also, as mentioned in the release post text copied above, it is possible to run valetudo-mapper in just map parser (converter) mode.

**Comment by nicedevil007** [comment]
Isn't it possible @ this time to let your node check if the incoming msg is buffer or a string and then let it decide witch modus should be used to draw the map in Node-RED?

Tryed to figure out how to "hotfix" it by myself but I'm to new into this to find a suitable node to change the buffer into string :(

**Comment by alexkn** [comment]
I have added the valetudo-parse-binmap node.
It converts the binary buffer to the old JSON string format.
You have to put it between your mqtt and map-png node.

**Comment by nicedevil007** [comment]
Worked perfect for me! Problem solved, one of the good developer here <3 :)
