### ISSUE TITLE
Path is never drawn (Dreame D9, Valetudo 2022.05)

### ISSUE THREAD

**Issue by jonasc** [alexkn/node-red-contrib-valetudo#23]
Robot: Dreame D9
Valetudo 2022.05

Thanks for the nice flow! I started using it for the first time with my Dreame D9 and noticed that the path is never drawn. It does not matter whether I enable or disable the "Draw Path" option. All other options (draw robot, draw charger, scale) do work (I did not check cropping as I don't need it).

Could it be that this has to do with Dreame using multiple paths instead of a single one, see https://github.com/Hypfer/Valetudo/releases/tag/2021.11.1 under "Bugfixes" > "Dreame paths".

**Comment by alexkn** [comment]
Yes, it will only draw the first path entity.

https://github.com/alexkn/node-red-contrib-valetudo/blob/690ecddf1a0c33122b44a6c06d459ac10bdbee30/lib/MapDrawer.js#L69-L73

**Comment by alexkn** [comment]
should be fixed in [v3.1.1](https://github.com/alexkn/node-red-contrib-valetudo/releases/tag/v3.1.1)

**Comment by jonasc** [comment]
It works like a charm! Thanks a lot for the quick fix and your work on the node!
