### ISSUE TITLE
Map not working after update to Valetudo-RE 0.9 with firmware 2008

### ISSUE THREAD

**Issue by nicedevil007** [alexkn/node-red-contrib-valetudo#5]
Hey AlexKn,

I've updated to latest Version of ValetudoRE 0.9 and the Mapdrawing in your node isn't working anymore because Roborock changed something in their firmware.

@rand256 gave me a hint for this but I don't know what to change :(

Maybe you can take a look at this?
[https://github.com/rand256/valetudo/issues/107#issuecomment-587084245](url)

**Comment by alexkn** [comment]
I think I can change that, but I have to be careful not to break the compatibility with the standard valetudo/old firmwares.
However, I don't have a Valetudo-RE, so I can't test properly.
Can you redirect the mqtt output to a file with a file out node, so that I can test it with a file in node?

**Comment by nicedevil007** [comment]
[mqtt_valetudo.txt](https://github.com/alexkn/node-red-contrib-valetudo/files/4236028/mqtt_valetudo.txt)

Here we go :)

**Comment by alexkn** [comment]
Is that picture correct for your data?
In particular robot and charger position?
The path is really short, I think its one pixel behind the robot.

I wrote a few unit tests to automatically test the different firmware versions, can I include your data there?

![FW2008_RE0 9 0](https://user-images.githubusercontent.com/645022/75091152-7cfbea00-556a-11ea-959a-306e7bcd79f1.png)

**Comment by nicedevil007** [comment]
That looks great :) yeah was just one message I put in the file :)
Could we change the colors depending on the skin that is used in valetudo-RF?

Like this:

![image](https://user-images.githubusercontent.com/17103076/75091630-d0bd0200-556f-11ea-8f6b-97b9e0526d4a.png)

**Comment by alexkn** [comment]
Please open a new issue for the colors.

**Comment by alexkn** [comment]
fixed with https://github.com/alexkn/node-red-contrib-valetudo/commit/4eed841129e087f53592aad7e218831bae9adb29
